### ISSUE TITLE
add support for security ACL REST ?

### ISSUE THREAD

**Issue by landryb** [jericks/geoserver-shell#8]
Hi,do you plan to add support for the upcoming security ACL REST API in 2.8, documented in http://docs.geoserver.org/latest/en/user/rest/api/accesscontrol.html ?

**Comment by jericks** [comment]
Looks like a good idea.  Do you have time to tackle this?  I would gladly accept a pull request.

**Comment by landryb** [comment]
whoa, awesome, many thanks! I'll make sure to testdrive this !

**Comment by landryb** [comment]
Fwiw, i've finally been able to deploy 2.8.1, and this works perfectly, so thanks again :)
