### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by virjay** [jericks/geoserver-shell#9]
I have centos 6.6. I installed maven using the yum repo from http://blog.gluster.org/2013/08/yum-install-maven-yes-you-can/ then I followed the instructions and it produced 119 failures and 66 failures.

'[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project geoserver-shell: There are test failures.'

**Comment by jericks** [comment]
All tests pass on my Mac and under Travis CI.  Can you make sure you are using Maven 3 and Java 7?
